progcomp/models/problem.py
import os
import json
import re
import typing
from typing import Optional

import sqlalchemy as sa
from sqlalchemy import ForeignKey, ForeignKeyConstraint, UniqueConstraint, func
from sqlalchemy.orm import relationship

from progcomp.models.utils import Status, Visibility, auto_str

if typing.TYPE_CHECKING:
    from progcomp.models.submission import *

from ..database import Base, db


@auto_str
class Problem(Base):
    __tablename__ = "problems"

    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.String)
    progcomp_id = sa.Column(sa.Integer, ForeignKey("progcomps.id"))
    visibility = sa.Column(
        sa.Enum(Visibility),
        nullable=False,
        default=Visibility.OPEN,
        server_default="OPEN",
    )
    __table_args__ = (
        sa.UniqueConstraint("name", "progcomp_id", name="unq_problems_name"),
    )

    tests = relationship("Test", back_populates="problem", order_by="Test.name")
    submissions = relationship("Submission", back_populates="problem")
    progcomp = relationship("Progcomp", back_populates="problems")

    @property
    def path(self) -> str:
        return os.path.join(os.getcwd(), "problems", self.progcomp.name, self.name)

    @property
    def visible(self) -> Visibility:
        return min(self.visibility, self.progcomp.visible)

    @property
    def open(self) -> bool:
        return self.visible == Visibility.OPEN

    def update(self) -> None:
        print(f"\x1b[32mupdate({self})\x1b[0m")

        input_path = os.path.join(
            os.getcwd(),
            "problems",
            self.progcomp.name,
            self.name,
            "input",
        )

        output_path = os.path.join(
            os.getcwd(),
            "problems",
            self.progcomp.name,
            self.name,
            "output",
        )

        old = set((t.name, t.ext) for t in self.tests)

        def check(test_input_filename: str) -> Optional[tuple[str, str]]:
            if os.path.isfile(
                os.path.join(
                    output_path,
                    (
                        test_input_filename
                        if not test_input_filename.endswith(".in")
                        else test_input_filename.removesuffix(".in") + ".out"
                    ),
                )
            ):
                match = re.search(r"^(.*)\.(.*)$", test_input_filename)
                return match.group(1), match.group(2)
            return None

        new = set(map(check, os.listdir(input_path)))
        new = set(s for s in new if s is not None)

        print("Old new", old, new)
        for test_name, test_ext in old - new:
            print(f"\x1b[32m{test_name}\x1b[0m")
            test = self.get_test(test_name)
            if test:
                db.session.delete(test)
                print("Removing Test", test)
        for test_name, test_ext in new - old:
            db.session.add(
                test := Test(problem_id=self.id, name=test_name, ext=test_ext)
            )
            print("Adding Test", test)

        db.session.commit()

        # Check for Config
        config_path = os.path.join(
            os.getcwd(),
            "problems",
            self.progcomp.name,
            self.name,
            "config.json",
        )

        if os.path.isfile(config_path):
            with open(config_path) as f:
                config = json.load(f)

            # Ensure Config is up to date
            for test_name, test_ext in new:
                test_max = config[test_name]["max"]
                test_weight = config[test_name]["weight"]
                (test := self.get_test(test_name)).max_score = test_max
                test.weight = test_weight

        db.session.commit()
        db.session.flush()
        print(f"\x1b[36mTests: {self.tests}\x1b[0m")

    def get_test(self, name: str) -> Optional["Test"]:
        return (
            db.session.query(Test)
            .where(Test.problem_id == self.id)
            .where(Test.name == name)
            .first()
        )


@auto_str
class Test(Base):
    __tablename__ = "tests"

    id = sa.Column(sa.Integer, primary_key=True)
    problem_id = sa.Column(sa.Integer, ForeignKey(Problem.id))
    name = sa.Column(sa.String, nullable=False)
    ext = sa.Column(sa.String, nullable=False)
    max_score = sa.Column(sa.Integer, nullable=True)
    weight = sa.Column(sa.Float, nullable=True)

    problem = relationship(Problem, back_populates="tests")
    submissions = relationship("Submission", back_populates="test")

    __table_args__ = (sa.UniqueConstraint("name", "problem_id", name="unq_tests_name"),)

    @property
    def input_path(self) -> str:
        return os.path.join(self.problem.path, "input", self.name + "." + self.ext)

    @property
    def ranked_submissions(self) -> list["Submission"]:
        from progcomp.models import Submission

        submissions = (
            db.session.query(Submission).where(Submission.test_id == self.id).all()
        )

        team_scores: dict[str, "Submission"] = {}

        for sub in submissions:
            if sub.status not in [Status.CORRECT, Status.PARTIAL, Status.SCORED]:
                continue
            current = team_scores.get(sub.team.name)
            # We take earliest submission with highest score
            if (
                not current
                or (sub.score > current.score)
                or (sub.score == current.score and sub.timestamp < current.timestamp)
            ):
                team_scores[sub.team.name] = sub

        sub_list = list(team_scores.values())
        sub_list.sort(key=lambda s: (-s.score, s.timestamp))
        print(sub_list)
        return sub_list

progcomp/routes.py
import os
import re
from datetime import datetime
from typing import Union

from flask import (
    Blueprint,
    jsonify,
    redirect,
    render_template,
    request,
    send_from_directory,
    session,
    url_for,
)
from werkzeug.utils import secure_filename
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.wrappers.response import Response

import markdown
from uuid import uuid4 as uuid

import requests_oauthlib

FlaskResponse = Union[Response, str]

from .database import db
from .models import *

# from .adapters import GameUIAdapter
from .session import *


def get_pc() -> Progcomp:
    name = session.get(PROGCOMP_SESSION_KEY)
    pc = db.session.query(Progcomp).where(Progcomp.name == name).first()
    return pc


bp = Blueprint("progcomp", __name__)


def partition(items: list, func: Callable, order=[]) -> list:
    results = defaultdict(list)
    for item in order:
        results[item] = []
    for item in items:
        results[func(item)].append(item)
    return {k: v for k, v in results.items() if v}


def get_progcomp_list():
    pcs = db.session.query(Progcomp).order_by(Progcomp.start_time).all()
    pcs = [pc for pc in pcs if pc.visible]

    parts = partition(pcs, lambda pc: pc.category, ["Active", "Upcoming", "Archived"])
    for p in parts.items():
        print(p)
    return parts


@bp.route("/")
def menu() -> FlaskResponse:
    pc = get_pc()
    username = session.get(USERNAME_SESSION_KEY)
    if (not pc) and username:
        return redirect(url_for("progcomp.logout"))
    partitions = get_progcomp_list()
    return render_template(
        "menu.html", progcomp=pc, partitions=partitions, username=username
    )


def verify_input(inp: Optional[str], max_len: int = 100) -> bool:
    return not (
        inp is None
        or inp == ""
        or inp.isspace()
        or len(inp) > max_len
        or not re.match(r"^[A-Za-z0-9_]+$", inp)
    )


@bp.route("/auth/callback")
def uwcs_callback():

    print("==================== CALLBACK ====================")

    keycloak = requests_oauthlib.OAuth2Session(os.environ.get("CLIENT_ID"))
    keycloak.fetch_token(
        os.environ.get("TOKEN_URL"),
        client_secret=os.environ.get("CLIENT_SECRET"),
        authorization_response=request.url,
    )

    user_info = keycloak.get(os.environ.get("USERINFO_URL")).json()
    warwick_id = user_info["uni_id"]

    print("WARWICK ID : " + warwick_id)

    sess = (
        db.session.query(LoginSession)
        .where(LoginSession.id == session.get(START_ID))
        .first()
    )

    username, password, pc_name = (sess.username, sess.passwd, sess.pc_name)

    db.session.delete(sess)
    db.session.commit()

    session[START_ID] = None

    # Get ProgComp
    pc = db.session.query(Progcomp).where(Progcomp.name == pc_name).first()
    if pc is None or not pc.visible:
        return redirect(url_for("progcomp.menu"))

    # Check password against potentially existing team
    team = pc.get_team(username)
    if team:
        if not check_password_hash(team.password, password):
            return redirect(url_for("progcomp.menu"))

        # Reject if they aren't a member, and there's no space for more
        elif (
            warwick_id not in (ids := team.member_ids)
            and len(ids) >= pc.max_team_members
        ):
            return redirect(url_for("progcomp.menu"))

        elif len([team for team in pc.all_teams if warwick_id in team.member_ids]) > 1:
            return redirect(url_for("progcomp.menu"))

        elif warwick_id not in ids:
            team.add_member(warwick_id)

    else:
        team = pc.add_team(username, generate_password_hash(password))
        team.add_member(warwick_id)

    # Save their username
    session[USERNAME_SESSION_KEY] = username
    session[PROGCOMP_SESSION_KEY] = pc_name

    return redirect(url_for("progcomp.submissions"))


@bp.route("/start", methods=["POST"])
def start() -> FlaskResponse:
    """
    When someone hits the 'start' button
    """
    # Check username and password are in a valid format
    username = request.form.get("username")
    print(username)
    if username is None or not verify_input(username, 100):
        return redirect(url_for("progcomp.menu"))

    password = request.form.get("password")
    print(password)
    if password is None or not verify_input(password, 30):
        return redirect(url_for("progcomp.menu"))

    pc_name = request.form.get("progcomp")
    print(pc_name)
    if pc_name is None or not verify_input(pc_name, 50):
        return redirect(url_for("progcomp.menu"))

    # Record Login
    start_id = str(uuid())
    session[START_ID] = start_id

    db.session.add(
        LoginSession(id=start_id, username=username, passwd=password, pc_name=pc_name)
    )
    db.session.commit()

    # Redirect to UWCS Auth
    keycloak = requests_oauthlib.OAuth2Session(os.environ.get("CLIENT_ID"))
    authorization_url, _ = keycloak.authorization_url(
        os.environ.get("AUTHORIZATION_BASE_URL")
    )

    return redirect(authorization_url)


@bp.route("/logout", methods=["GET", "POST"])
def logout() -> FlaskResponse:
    """
    When someone hits the 'logout' button
    """
    # Save their username
    session[USERNAME_SESSION_KEY] = None
    session[PROGCOMP_SESSION_KEY] = None
    if sess_key := session.get(ADMIN_SESSION_KEY):
        db.session.query(AdminSession).where(AdminSession.id == sess_key).delete()
        db.session.commit()
        session[ADMIN_SESSION_KEY] = None

    return redirect(url_for("progcomp.menu"))


@bp.route("/submissions", methods=["GET"])
def submissions() -> FlaskResponse:
    """
    The submission page / home page for the contest
    """

    if (pc := get_pc()) is None:
        return redirect(url_for("progcomp.menu"))

    username = session.get(USERNAME_SESSION_KEY)
    if not username:
        return redirect(url_for("progcomp.menu"))
    team = pc.get_team(username)
    if not team:
        return redirect(url_for("progcomp.menu"))

    # List out team submission info
    return render_template(
        "submissions.html", team=team, progcomp=pc, username=username
    )


@bp.route("/problems/<string:p_name>", methods=["GET", "POST"])
def problem(p_name) -> FlaskResponse:
    """
    Retrieve the page for a problem
    """
    if (pc := get_pc()) is None:
        return redirect(url_for("progcomp.menu"))

    username = session.get(USERNAME_SESSION_KEY)
    if not username:
        return redirect(url_for("progcomp.menu"))

    problem = pc.get_problem(p_name)
    if not problem or not problem.visible:
        return redirect(url_for("progcomp.submissions"))

    if request.method == "GET":

        content_path = os.path.join(
            os.getcwd(),
            "problems",
            problem.progcomp.name,
            problem.name,
            problem.name + ".md",
        )

        content = None
        if os.path.isfile(content_path):
            with open(content_path) as f:
                content = markdown.markdown(
                    f.read(), extensions=["nl2br", "fenced_code", "tables"]
                )

        return render_template(
            "problem.html",
            username=username,
            problem=problem,
            progcomp=pc,
            problem_description=content,
        )

    else:  # POST (Submission Handling)
        if not problem.open:
            return redirect(request.url)

        if "output" not in request.files or "script" not in request.files:
            return redirect(request.url)

        # If user doesn't select a file, browser submits empty file.
        output = request.files.get("output")
        if not output or output.filename == "":
            return redirect(request.url)

        script = request.files.get("script")
        if not script or script.filename is None or script.filename == "":
            return redirect(request.url)
        script_name = secure_filename(script.filename)

        test = request.form.get("test_select")
        if not test:
            return redirect(request.url)

        match = re.search(r"^(.*)\.(.*)$", test)
        test_name = match.group(1)
        test_ext = match.group(2)

        time = datetime.now()
        time_str = time.strftime("%Y-%m-%d_%H-%M-%S")

        # need to folder w/ timestamp on path
        path = os.path.join(
            os.getcwd(), "submissions", pc.name, username, p_name, test_name, time_str
        )

        os.makedirs(path, exist_ok=True)

        # Upload files
        output.save(os.path.join(path, "output.txt"))
        script.save(os.path.join(path, script_name))

        pc.make_submission(path, username, p_name, test_name, test_ext, timestamp=time)

        return redirect(url_for("progcomp.submissions"))


@bp.route("/problems/asset/<string:prob>/<string:file>", methods=["GET"])
def asset(prob: str, file: str):
    prob = secure_filename(prob)
    file = secure_filename(file)

    path = os.path.join(os.getcwd(), "problems", get_pc().name, prob, "assets")

    return send_from_directory(directory=path, path=file)


@bp.route("/download/<string:p_name>/<string:t_name>", methods=["GET"])
def download(p_name, t_name) -> FlaskResponse:
    """
    Download a specified problem input
    """

    if (pc := get_pc()) is None:
        print("case 1 (No ProgComp)")
        return redirect(url_for("progcomp.menu"))
    if (problem := pc.get_problem(p_name)) is None or not problem.visible:
        print(f"redirecting after {p_name}")
        return redirect(url_for("progcomp.menu"))

    match = re.search(r"^(.*)\.(.*)$", t_name)
    test_name = match.group(1)
    ext = match.group(2)

    if (test := problem.get_test(test_name)) is None:
        print("case 3 (Test no registered) with", test_name)
        return redirect(url_for("progcomp.menu"))

    path = os.path.join(problem.path, "input")
    fname = f"{test.name}.{test.ext}"
    if not os.path.exists(os.path.join(path, fname)):

progcomp/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <title>{% block title %}{% endblock %} - UWCS Challenge</title>
  
  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">

  <!-- Cookies -->
  <script src=" https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js "></script>
  
  <!-- MathJax -->
  <script>
    MathJax = {
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']], // Enable single dollar signs
        displayMath: [['$$', '$$'], ['\\[', '\\]']], // Display math (already enabled by default)
        processEscapes: true,   // Use \$ to render literal dollar signs
        processEnvironments: true,
        processRefs: true,
        digits: /^(?:[0-9]+(?:\{,\}[0-9]{3})*(?:\.[0-9]*)?|\.[0-9]+)/,
        tags: 'ams'  // Use AMS numbering
      }
    };  
      
  </script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

  <!-- Local Assets -->
  <link rel="shortcut icon" href="{{ url_for('static', filename='challenge_icon.svg') }}" type="image/x-icon">
  <script src="{{ url_for('static', filename='countdown.js') }}"></script>
  <script src="{{ url_for('static', filename='darkmode.js') }}"></script>

  {% block head %}{% endblock %}
</head>

<body>
  <div class="container min-vh-100 d-flex flex-column align-items-center">
    <nav class="w-100 navbar navbar-expand-lg rounded-bottom bg-primary-subtle" style="min-width: fit-content">
      <div class="container-fluid align-items-center">
        <a class="navbar-brand" href="/">
          {% include "chall_logo.html" %}
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03"
          aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor03">
          <ul class="navbar-nav d-flex w-100">
            <li class="nav-item">
              <a class="nav-link text-nowrap" href="/#">
                {% if progcomp %}
                <span class="d-lg-none ms-lg-0">Competition: </span>{{ progcomp.name }}
                {% else %}
                Login
                {% endif %}
              </a>
            </li>
            <div class="vr d-none d-lg-block mx-1"></div>
            <li class="nav-item">
              <a class="nav-link" href="/general_advice">Advice</a>
            </li>
            {% if progcomp %}
            <div class="vr d-none d-lg-block mx-1"></div>
            <li class="nav-item">
              <a class="nav-link" href="/submissions">Submissions</a>
            </li>
            {% for p in progcomp.visible_problems %}
            <li class="nav-item">
              <a class="nav-link" href="/problems/{{ p.name }}">Problem&nbsp;{{ p.name }}</a>
            </li>
            {% endfor %}
            {% if progcomp.show_leaderboard %}
            <li class="nav-item">
              <a class="nav-link" href="/leaderboard">Leaderboard</a>
            </li>
            {% endif %}
            {% endif %}
            <div class="vr ms-md-auto d-none d-lg-block "></div>
            <li class="nav-item ms-lg-2">
              <a id="dark-mode" class="nav-link ml-1">
                <i class="bi-moon-fill" id="dark-mode-icon"></i>
                <span class="d-lg-none ms-2 ms-lg-0">Toggle Dark Mode</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header class="w-100 d-flex flex-column gap-3 px-3">
      {% for alert in progcomp.alerts %}
      <div class="alert alert-info px-3 py-2 mt-3 mb-0" role="alert">
        {% if alert.title %}<h5 class="alert-heading">{{ alert.title }}</h5>{% endif %}
        {% if alert.text %}{{ alert.text }}</h4>{% endif %}
      </div>
      {% endfor %}
    </header>

    <article id="content" class="w-100">
      {% block content %}{% endblock %}
    </article>

    <footer class="w-100 mt-auto d-flex flex-wrap justify-content-between gap-2 py-3 mt-4 border-top">
      <div class="flex-grow-1 flex-md-grow-0 mb-0 text-muted">
        {% if progcomp %}
        {% set visibility = progcomp.visible|string() %}
        {% if visibility == "Open" %}
        {% set row_color = 'text-bg-success' %}
        {% elif visibility == "Closed" %}
        {% set row_color = 'text-bg-danger' %}
        {% else %}
        {% set row_color = "text-bg-warning" %}
        {% endif %}
        {{ progcomp.name }}
        <small class="badge {{ row_color }}" style="height: fit-content">{{ progcomp.visible }}</small> |
        {% if username %}
        Team: {{ username }} |
        {% endif %}
        <span id="countdown">Countdown soonTM</span>
        {% endif %}
      </div>
      <div class="d-md-none" style="flex-basis: 100%; height: 0"></div>
      <a class="d-flex text-decoration-none" href="https://uwcs.co.uk">
        {% include "uwcs_logo.html" %}
      </a>

      <ul class="nav justify-content-end list-unstyled d-flex">
        <li class="ms-3">
          <a class="text-muted" href="https://github.com/UWCS/progcomp-web"><i class="bi-github"
              aria-hidden="true"></i></a>
        </li>
        <li class="ms-3">
          <a class="text-muted" href="https://discord.uwcs.co.uk"><i class="bi-discord" aria-hidden="true"></i></a>
        </li>
        <li class="ms-3">
          <a class="text-muted" href="https://uwcs.co.uk"><i class="bi-globe" aria-hidden="true"></i></a>
        </li>
      </ul>
    </footer>
  </div>
</body>

</html>

progcomp/templates/menu.html
{% extends 'base.html' %}

{% block head %}
<script src="{{ url_for('static', filename='progcomp-info.js') }}"></script>
{% endblock %}

{% block title %}Home{% endblock %}

{% macro progcomp_badge(progcomp) -%}
{% set visibility = progcomp.visible|string() %}
{% if visibility == "Open" %}{% set row_color = 'text-bg-success' %}
{% elif visibility == "Closed" %}{% set row_color = 'text-bg-danger' %}
{% else %}{% set row_color = "text-bg-warning" %}
{% endif %}
<small class="badge {{ row_color }}">{{ progcomp.visible }}</small>
{%- endmacro %}

{% block content %}

<div class="d-flex flex-column align-items-center gap-3 my-5">
    <img class="mw-100 p-2" style="width: 500px" src="static/challenge_logo.svg" alt="Logo"></img>
    {% if not username %}
    <form class="mw-100" style="width: 300px" action="{{ url_for('progcomp.start') }}" method="POST">
        <div class="form-group my-3">
            <label for="progcomp">Competition</label>
            <select class="form-select" id="progcomp" name="progcomp" {% if not partitions %}disabled{% endif %}>
                {% for (title, items) in partitions.items() %}
                <optgroup label="{{ title }}">
                    {% for progcomp in items %}
                    <option value="{{ progcomp.name }}">{{ progcomp.name }}</option>
                    {% endfor %}
                </optgroup>
                {% endfor %}
            </select>
            {% for (title, items) in partitions.items() %}
            {% for progcomp in items %}
            <small id="progcomp-help-{{ progcomp.name }}" class="form-text text-muted" hidden>
                {{ title }}
                {{ progcomp_badge(progcomp) }}
                {{ progcomp.time_str }}
            </small>
            {% endfor %}
            {% endfor %}
        </div>

        <div class="form-group my-3">
            <label for="username">Team Name</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter your team's name">
            <small id="username-help" class="form-text text-muted">Must be alphanumeric and not contain
                spaces.</small>
        </div>
        <div class="form-group my-3">
            <label for="password">Pass Phrase</label>
            <input type="password" class="form-control" id="password" name="password"
                placeholder="Create/Enter your pass phrase">
            <small id="username-help" class="form-text text-muted">Must be alphanumeric and not contain
                spaces.</small>
        </div>
        <div class="form-group text-center my-3">
            <button type="submit" class="btn btn-success btn-lg">Join this Team</button>
        </div>
    </form>
    {% else %}
    <form class="mw-100" style="width: 300px" action="{{ url_for('progcomp.logout') }}" method="POST">
        <div class="form-group my-3">
            <label for="progcomp">Competition</label>
            <select class="form-select" id="progcomp" name="progcomp" disabled
                style="background: var(--bs-form-control-disabled-bg);">
                <option selected>{{ progcomp.name }}</option>
            </select>

            <small id="progcomp-help-{{ progcomp.name }}" class="form-text text-muted">
                {{ progcomp.category }}
                {{ progcomp_badge(progcomp) }}
                {{ progcomp.time_str }}
            </small><br>
        </div>

        <div class="form-group my-3">
            <label for="username">Team Name</label>
            <input type="text" class="form-control" value="{{ username }}" disabled>
            <small id="username-help" class="form-text text-muted">Must be alphanumeric and not contain
                spaces.</small>
        </div>
        <div class="form-group text-center my-3">
            <button type="submit" class="btn btn-danger btn-lg">Log out</button>
        </div>
    </form>

    {% endif %}
    <div class="mt-3">
        <h2>Instructions</h2>
        <ol>
            <li>Pick a team name and passphrase, and share this among your team (each progcomp has separate teams).</li>
            <li>Download the problems PDF under Submissions.</li>
            <li>Each challenge will be listed along the top. Click on each to view the input test data.</li>
            <li>Once you have some solutions, upload your script's output (and the script for later verification).</li>
            <li>Your results for each problem should be available under Submissions.</li>
        </ol>
    </div>
</div>

{% endblock %}

progcomp/templates/problem.html
{% extends 'base.html' %}

{% block title %}Problem {{ problem.name }}{% endblock %}

{% block head %}
<script src="{{ url_for('static', filename='keep_selected.js') }}"></script>
<style>
    #prob_desc code {
        color: palevioletred;
    }

    #prob_desc h1:first-of-type {
        font-size: calc((1.375rem + 1.5vw) * 1.3);
        font-weight: bolder;
    }

    #prob_desc img {
        display: block;
        margin: 0 auto;
    }
</style>
{% endblock %}

{% block content %}

<div class="row pt-5 mb-4" id="header">
    <h3>Problem <b>{{ problem.name }}</b></span></h3>
</div>

{% if problem_description %}
    <div class="card p-4 mb-4" id="prob_desc">
        {{ problem_description | safe }}
    </div>
{% endif %}

<h4>Download Input Test Data</h4><br>
<div class="d-flex flex-wrap gap-2">
    {% for test in problem.tests %}
    <a class="flex-grow-1 btn btn-primary" style="min-width: max-content;"
        href="{{ url_for('progcomp.download', p_name=problem.name, t_name=test.name+'.'+test.ext) }}">
        <i class="bi-download me-1"></i>&nbsp;{{ test.name }}</a>
    {% endfor %}
</div>

<hr>
<br>
{% if problem.open %}
<form method=post enctype=multipart/form-data>
    <h4>Submit Results</h4>
    <div class="d-flex flex-wrap align-items-center gap-4">
        <div>
            <label for="test_select" class="form-label m-0 fw-bold" style="min-width: max-content">Select Input
                Data:</label>
        </div>
        <div class="flex-grow-1">
            <select class="form-select" id="test_select" name="test_select">
                {% for test in problem.tests %}
                <option value="{{ test.name+'.'+test.ext }}">{{ test.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <button id="prob_submit" type="submit" class="btn btn-primary btn-lg align-bottom">Submit</button>
        </div>
    </div>
    <br>
    <div class="d-flex flex-wrap gap-2">
        <div class="p-2 flex-grow-1">
            <label for="output" class="form-label fw-bold">Upload Solution Results</label>
            <input class="form-control" type=file name=output accept=".txt,.out">
        </div>
        <div class="p-2 flex-grow-1">
            <label for="script" class="form-label"><b>Upload Script</b> (for verification)</label>
            <input class="form-control" type=file name=script>
        </div>
    </div>
    <br>
</form>

{% else %}
<h4>Submissions Closed!</h4>
{% endif %}

{% endblock %}